from tkinter import *
root = Tk()
fr1 = Frame(root)
fr1.pack(side = 'top')
btn_1 = Button(fr1, text = 'Button1', width = 10, height = 3, bg = 'blue', fg = 'black', font = 'arial 14')
btn_2 = Button(fr1, text = 'Button2', width = 10, height = 3, bg = 'yellow', fg = 'black', font = 'arial 16')
root.geometry('500x300')
btn_1.pack(side = 'left')
btn_2.pack(side = 'right', padx = 5)
root.mainloop()
